### ISSUE TITLE
Parlour is broken with Ruby 2.4 & Sorbet master

### ISSUE THREAD

**Issue by manhhung741** [AaronC81/parlour#66]
**Describe the bug**
Build failure with Ruby 2.4 & Sorbet master. IDK if this is a sorbet bug or we need to make changes in parlour. Maybe the right fix is to file issue to Sorbet team and fix it.

**To Reproduce**
See https://travis-ci.com/chanzuckerberg/sorbet-rails/jobs/295030504
It seems simply requiring `parlour` breaks the code

**Additional information**
Add any other information about the problem here. Please include the version of Parlour you're using as well as the versions of any plugins.

```
Failure/Error: require('parlour')
NoMethodError:
  private method `define_method' called for Parlour::TypeParser::IntermediateSig:Class
  Did you mean?  redefine_method
# /home/travis/.rvm/gems/ruby-2.4.6/gems/sorbet-runtime-0.5.5417/lib/types/props/has_lazily_specialized_methods.rb:66:in `enqueue_lazy_method_definition!'
# /home/travis/.rvm/gems/ruby-2.4.6/gems/sorbet-runtime-0.5.5417/lib/types/private/methods/call_validation.rb:126:in `call'
# /home/travis/.rvm/gems/ruby-2.4.6/gems/sorbet-runtime-0.5.5417/lib/types/private/methods/call_validation.rb:126:in `validate_call'
# /home/travis/.rvm/gems/ruby-2.4.6/gems/sorbet-runtime-0.5.5417/lib/types/private/methods/_methods.rb:238:in `block in _on_method_added'
# /home/travis/.rvm/gems/ruby-2.4.6/gems/sorbet-runtime-0.5.5417/lib/types/props/serializable.rb:168:in `add_prop_definition'
# /home/travis/.rvm/gems/ruby-2.4.6/gems/sorbet-runtime-0.5.5417/lib/types/props/decorator.rb:424:in `prop_defined'
# /home/travis/.rvm/gems/ruby-2.4.6/gems/sorbet-runtime-0.5.5417/lib/types/private/methods/_methods.rb:240:in `call'
# /home/travis/.rvm/gems/ruby-2.4.6/gems/sorbet-runtime-0.5.5417/lib/types/private/methods/_methods.rb:240:in `block in _on_method_added'
# /home/travis/.rvm/gems/ruby-2.4.6/gems/sorbet-runtime-0.5.5417/lib/types/props/_props.rb:109:in `prop'
# /home/travis/.rvm/gems/ruby-2.4.6/gems/parlour-2.0.0/lib/parlour/type_parser.rb:262:in `<class:IntermediateSig>'
# /home/travis/.rvm/gems/ruby-2.4.6/gems/parlour-2.0.0/lib/parlour/type_parser.rb:261:in `<class:TypeParser>'
# /home/travis/.rvm/gems/ruby-2.4.6/gems/parlour-2.0.0/lib/parlour/type_parser.rb:17:in `<module:Parlour>'
# /home/travis/.rvm/gems/ruby-2.4.6/gems/parlour-2.0.0/lib/parlour/type_parser.rb:15:in `<top (required)>'
# /home/travis/.rvm/gems/ruby-2.4.6/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
# /home/travis/.rvm/gems/ruby-2.4.6/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `block in require'
# /home/travis/.rvm/gems/ruby-2.4.6/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:259:in `load_dependency'
# /home/travis/.rvm/gems/ruby-2.4.6/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
# /home/travis/.rvm/gems/ruby-2.4.6/gems/parlour-2.0.0/lib/parlour.rb:31:in `<top (required)>'
# /home/travis/.rvm/gems/ruby-2.4.6/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
# /home/travis/.rvm/gems/ruby-2.4.6/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `block in require'
# /home/travis/.rvm/gems/ruby-2.4.6/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:259:in `load_dependency'
# /home/travis/.rvm/gems/ruby-2.4.6/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
# ./lib/sorbet-rails/model_rbi_formatter.rb:2:in `<top (required)>'
```

**Comment by AaronC81** [comment]
This is now fixed in Sorbet!
